Repository FISCO-BCOS/bcos-utilities, pull requests merged in 2022-01, with the labels that each got.

#8 copy bcos-cmake-scripts to bcos-utilities in-case-of fetch failed
  .clang-format
  .github/workflows/coverage.yml
  bcos-cmake-scripts/BuildDocs.cmake
  bcos-cmake-scripts/CompilerSettings.cmake
  bcos-cmake-scripts/HunterGate.cmake
  bcos-cmake-scripts/InstallConfig.cmake
  bcos-cmake-scripts/Options.cmake
  tests/CMakeLists.txt
Labels: optimize-download, compile

#9 remove bcos-cmake-scripts
  CMakeLists.txt
  bcos-cmake-scripts/CompilerSettings.cmake
  bcos-cmake-scripts/Coverage.cmake
Labels: optimize-download, sync-code

#10 fix compile
  .github/workflows/coverage.yml
  CMakeLists.txt
  bcos-cmake-scripts/.Doxyfile.in
  bcos-cmake-scripts/BuildDocs.cmake
Labels: compile, bug fix, ci

#11 fix windows compile
  bcos-utilities/FixedBytes.h
Labels: compile, windows
